services:
  - type: worker
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 run.py"
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: 7839007712:AAERxGdintfRM6xMAwoTWVtOipzRPvyf3Gs
      - key: OWNER_CHAT_ID
        value: 5643687492 